### ISSUE TITLE
Cannot install Octave on High Sierra

### ISSUE THREAD

**Issue by sunqingyao** [schoeps/homebrew-science#4]
```
$ brew install schoeps/science/octave --with-java --with-qt --HEAD
Updating Homebrew...
Warning: Calling 'depends_on :hg' is deprecated!
Use 'depends_on "mercurial"' instead.
/usr/local/Homebrew/Library/Taps/schoeps/homebrew-science/octave.rb:12:in `block in <class:Octave>'
Please report this to the schoeps/science tap!

Warning: Calling 'depends_on :fortran' is deprecated!
Use 'depends_on "gcc"' instead.
/usr/local/Homebrew/Library/Taps/schoeps/homebrew-science/octave.rb:24:in `<class:Octave>'
Please report this to the schoeps/science tap!

==> Installing octave from schoeps/science
Warning: Calling 'depends_on :mpi' is deprecated!
Use 'depends_on "open-mpi"' instead.
/usr/local/Homebrew/Library/Taps/schoeps/homebrew-science/sundials27.rb:15:in `<class:Sundials27>'
Please report this to the schoeps/science tap!

==> Installing dependencies for schoeps/science/octave: sundials27, qt, sip, pyqt, qscintilla2
==> Installing schoeps/science/octave dependency: sundials27
Warning: Calling 'depends_on :fortran' is deprecated!
Use 'depends_on "gcc"' instead.
/usr/local/Homebrew/Library/Taps/schoeps/homebrew-science/sundials27.rb:14:in `<class:Sundials27>'
Please report this to the schoeps/science tap!

Warning: Calling 'depends_on :mpi' is deprecated!
Use 'depends_on "open-mpi"' instead.
/usr/local/Homebrew/Library/Taps/schoeps/homebrew-science/sundials27.rb:15:in `<class:Sundials27>'
Please report this to the schoeps/science tap!

==> Downloading https://computation.llnl.gov/projects/sundials/download/sundials
######################################################################## 100.0%
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG
==> make install
Warning: Calling 'depends_on :fortran' is deprecated!
Use 'depends_on "gcc"' instead.
/usr/local/Homebrew/Library/Taps/schoeps/homebrew-science/sundials27.rb:14:in `<class:Sundials27>'
Please report this to the schoeps/science tap!

Warning: Calling 'depends_on :mpi' is deprecated!
Use 'depends_on "open-mpi"' instead.
/usr/local/Homebrew/Library/Taps/schoeps/homebrew-science/sundials27.rb:15:in `<class:Sundials27>'
Please report this to the schoeps/science tap!

🍺  /usr/local/Cellar/sundials27/2.7.0: 315 files, 5MB, built in 1 minute 29 seconds
==> Installing schoeps/science/octave dependency: qt
==> Downloading https://homebrew.bintray.com/bottles/qt-5.10.1.high_sierra.bottl
######################################################################## 100.0%
==> Pouring qt-5.10.1.high_sierra.bottle.tar.gz
==> Caveats
We agreed to the Qt opensource license for you.
If this is unacceptable you should uninstall.

This formula is keg-only, which means it was not symlinked into /usr/local,
because Qt 5 has CMake issues when linked.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/qt/bin:$PATH"' >> ~/.zshrc

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/qt/lib
    CPPFLAGS: -I/usr/local/opt/qt/include
For pkg-config to find this software you may need to set:
    PKG_CONFIG_PATH: /usr/local/opt/qt/lib/pkgconfig

==> Summary
🍺  /usr/local/Cellar/qt/5.10.1: 9,375 files, 295.1MB
==> Installing schoeps/science/octave dependency: sip
==> Downloading https://homebrew.bintray.com/bottles/sip-4.19.8_1.high_sierra.bo
######################################################################## 100.0%
==> Pouring sip-4.19.8_1.high_sierra.bottle.tar.gz
==> Caveats
The sip-dir for Python is /usr/local/share/sip.
==> Summary
🍺  /usr/local/Cellar/sip/4.19.8_1: 16 files, 1.1MB
==> Installing schoeps/science/octave dependency: pyqt
==> Downloading https://homebrew.bintray.com/bottles/pyqt-5.10.1.high_sierra.bot
######################################################################## 100.0%
==> Pouring pyqt-5.10.1.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/pyqt/5.10.1: 985 files, 44.9MB
==> Installing schoeps/science/octave dependency: qscintilla2
==> Downloading https://homebrew.bintray.com/bottles/qscintilla2-2.10.3.high_sie
######################################################################## 100.0%
==> Pouring qscintilla2-2.10.3.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/qscintilla2/2.10.3: 138 files, 8.6MB
==> Installing schoeps/science/octave --HEAD --with-java --with-qt
Warning: Calling 'depends_on :hg' is deprecated!
Use 'depends_on "mercurial"' instead.
/usr/local/Homebrew/Library/Taps/schoeps/homebrew-science/octave.rb:12:in `block in <class:Octave>'
Please report this to the schoeps/science tap!

Warning: Calling 'depends_on :fortran' is deprecated!
Use 'depends_on "gcc"' instead.
/usr/local/Homebrew/Library/Taps/schoeps/homebrew-science/octave.rb:24:in `<class:Octave>'
Please report this to the schoeps/science tap!

Warning: Calling 'depends_on :mpi' is deprecated!
Use 'depends_on "open-mpi"' instead.
/usr/local/Homebrew/Library/Taps/schoeps/homebrew-science/sundials27.rb:15:in `<class:Sundials27>'
Please report this to the schoeps/science tap!

==> Cloning https://hg.savannah.gnu.org/hgweb/octave
Updating /Users/nalzok/Library/Caches/Homebrew/octave--hg
'import sitecustomize' failed; use -v for traceback
==> Checking out branch default
'import sitecustomize' failed; use -v for traceback
Error: no time information in ""
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/time.rb:254:in `make_time'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/time.rb:366:in `parse'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:1012:in `source_modified_time'
/usr/local/Homebrew/Library/Homebrew/resource.rb:116:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:114:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:92:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1872:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1090:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:109:in `block in install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:554:in `with_env'
/usr/local/Homebrew/Library/Homebrew/build.rb:106:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:187:in `<main>'
```

**Comment by schoeps** [comment]
I have joined forces with @dpo. He is maintaining (a subset of ) the formulas from the former homebrew/science tap compiled with openblas. Please uninstall this repo
`
brew untap schoeps/science
`
and install from @dpo's
`
brew tap dpo/openblas
brew install dpo/openblas/octave --verbose --with-java --devel --with-qt
`
This will give you version 4.3+ (d0221e3675ef).

**Comment by sunqingyao** [comment]
Unfortunately it still doesn't seem to work

```
❯ brew install dpo/openblas/octave --verbose --with-java --devel --with-qt > brewError.txt
'import sitecustomize' failed; use -v for traceback
'import sitecustomize' failed; use -v for traceback
Error: no time information in ""
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/time.rb:254:in `make_time'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/time.rb:366:in `parse'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:1012:in `source_modified_time'
/usr/local/Homebrew/Library/Homebrew/resource.rb:116:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:114:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:92:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1872:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1090:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:109:in `block in install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:554:in `with_env'
/usr/local/Homebrew/Library/Homebrew/build.rb:106:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:187:in `<main>'
```

And there is the content of brewError.txt

```
==> Installing octave from dpo/openblas
/usr/bin/sandbox-exec -f /tmp/homebrew20180316-74968-13m6378.sb nice /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/dpo/homebrew-openblas/octave.rb --verbose --devel --with-java --with-qt
==> Cloning https://hg.savannah.gnu.org/hgweb/octave
Updating /Users/nalzok/Library/Caches/Homebrew/octave--hg
/usr/local/opt/mercurial/bin/hg pull --update
pulling from https://hg.savannah.gnu.org/hgweb/octave
searching for changes
no changes found
==> Checking out revision d0221e3675ef
/usr/local/opt/mercurial/bin/hg archive --subrepos -y -r d0221e3675ef -t files /private/tmp/octave-20180316-74970-1o2vlwy
```

**Comment by schoeps** [comment]
These messages seem to be about your homebrew installation and not about octave. What happens if you install some other formula, e.g. `brew reinstall openblas --build-from-source`?

Actually, the `'import sitecustomize'` issue should have been fixed recently by https://github.com/Homebrew/brew/pull/3899. Can you do a `brew update`, `brew upgrade` and `brew doctor` just to make sure that your installation is fine?

... and please close the issue here and reopen it at http://github.com/dpo/homebrew-openblas/issues. I really like to delete this repository and just maintain the other one.

**Comment by sunqingyao** [comment]
https://github.com/dpo/homebrew-openblas/issues/53
